### ISSUE TITLE
Предложение по публикации 

### ISSUE THREAD

**Issue by DjonniStorm** [ycea/JATodo#1]
Выложи на GitHub Pages)
Вот простенький гайд: https://tproger.ru/articles/gajd-kak-razmestit-sajt-besplatno-na-github-pages

**Comment by ycea** [comment]
ну вот. Теперь я вижу насколько плохо это выглядит на мобильной версии XD
https://ycea.github.io/JATodo

**Comment by DjonniStorm** [comment]
> ну вот. Теперь я вижу насколько плохо это выглядит на мобильной версии XD https://ycea.github.io/JATodo

Все через это проходят xD
Попробуй помасштабировать этот сайтик для НИРСа, все сразу поплывёт)
https://djonnistorm.github.io/history/
 https://developer.mozilla.org/ru/docs/Web/CSS/@media 
https://www.google.com/amp/s/code-basics.com/ru/languages/css/lessons/media.amp
https://www.google.com/amp/s/htmlacademy.ru/blog/css/adaptive%3famp=1
